root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd"
  include_ext = ["go", "templ", "css"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_regex = ["_templ.go"]
  pre_cmd = ["templ generate"]
